name: e_commerce_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  persistent_bottom_nav_bar_v2: ^4.2.5
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  cloud_firestore: ^3.4.6
  google_sign_in: ^5.4.2
  flutter_facebook_auth: "^5.0.6"
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  flutter_login_facebook: ^1.6.2
  dio: ^4.0.6
  carousel_slider: ^4.1.1
  hexcolor: ^3.0.1
  shared_preferences: ^2.0.15
  google_maps_flutter: ^2.2.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.2.0
  animate_do: ^3.0.2
  cached_network_image: ^3.2.3
  google_fonts: ^3.0.1
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  conditional_builder_null_safety: ^0.0.6
  bottom_navy_bar: ^6.0.0
  flutter_localizations:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/


  
